version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - jonchang
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang
