version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jonchang
  allow:
    - dependency-type: production
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jonchang
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jonchang
