name: Bug Report
description: Create a report to help us improve
labels: [bug]
assignees:
  - jonchang
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Have you tried some common solutions to problems?
      options:
        - label: I've read the [Troubleshooting guide](https://jonchang.github.io/tact/troubleshooting/) and my issue isn't described there
          required: true
        - label: I've [installed the latest version](https://jonchang.github.io/tact/install/)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, run TACT in extra-verbose mode with `-vvv` and attach any logs.
      render: text
